### ISSUE TITLE
notebook where 'stage_2_study_to_data.pickle' was generated is missing?

### ISSUE THREAD

**Issue by wannasleepforever** [antorsae/rsna-intracranial-hemorrhage-detection-team-bighead#1]
I'm trying to understand how to do ensemble in fastai2. I've watched every notebook seeking how you created this file. But eventually couldn't find it. Can you please give some code or link to source where I can understand how to create such a file?
P.S. Thanks for this brilliant work. Your git project is the best among other winners.

**Comment by antorsae** [comment]
It's on https://github.com/antorsae/rsna-intracranial-hemorrhage-detection-team-bighead/tree/master/data

You may need to install git lfs as described in readme.

**Comment by wannasleepforever** [comment]
Thanks but I guess here is a little misunderstanding. I've installed everything already and all is good. However I want to know how this pickle file 'stage_2_study_to_data.pickle' was actually created. This question may seem odd but I do want to see in the code how it was built to 
borrow this method and use it in my own project some time

**Comment by antorsae** [comment]
See latest commit which adds the preprocessing to generate that missing pickle.
